//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociacaoCargoCompetencia
    {
        public int ID { get; set; }
        public int CargoRubiID { get; set; }
        public string CargoRubi { get; set; }
        public int AreaRubiID { get; set; }
        public string AreaRubi { get; set; }
        public Nullable<int> SetorRubiID { get; set; }
        public string SetorRubi { get; set; }
        public Nullable<int> CargoCompetenciaID { get; set; }
        public string CargoCompetencia { get; set; }
        public Nullable<int> AreaCompetenciaID { get; set; }
        public string AreaCompetencia { get; set; }
        public Nullable<int> SetorCompetenciaID { get; set; }
        public string SetorCompetencia { get; set; }
        public int CicloAvaliacao_ID { get; set; }
    
        public virtual CicloAvaliacao CicloAvaliacao { get; set; }
    }
}
