//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoGestor
    {
        public AvaliacaoGestor()
        {
            this.ContribuicaoColaborador = new HashSet<ContribuicaoColaborador>();
            this.ResultadoAtingidoColaborador = new HashSet<ResultadoAtingidoColaborador>();
        }
    
        public int ID { get; set; }
        public string Avaliacao { get; set; }
    
        public virtual ICollection<ContribuicaoColaborador> ContribuicaoColaborador { get; set; }
        public virtual ICollection<ResultadoAtingidoColaborador> ResultadoAtingidoColaborador { get; set; }
    }
}
