//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoColaborador
    {
        public AvaliacaoColaborador()
        {
            this.CompetenciaColaborador = new HashSet<CompetenciaColaborador>();
            this.ContribuicaoColaborador = new HashSet<ContribuicaoColaborador>();
            this.ObjetivoColaborador = new HashSet<ObjetivoColaborador>();
            this.PerformanceColaborador = new HashSet<PerformanceColaborador>();
            this.RecomendacaoColaborador = new HashSet<RecomendacaoColaborador>();
        }
    
        public int ID { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string JustificativaReprovacao { get; set; }
        public bool Aprovada { get; set; }
        public int CicloAvaliacao_ID { get; set; }
        public int Colaborador_ID { get; set; }
        public Nullable<int> GestorRubiID { get; set; }
        public int StatusAvaliacaoColaborador_ID { get; set; }
        public Nullable<int> CargoRubiID { get; set; }
        public Nullable<int> AreaRubiID { get; set; }
        public Nullable<int> SetorRubiID { get; set; }
    
        public virtual ICollection<CompetenciaColaborador> CompetenciaColaborador { get; set; }
        public virtual CicloAvaliacao CicloAvaliacao { get; set; }
        public virtual StatusAvaliacaoColaborador StatusAvaliacaoColaborador { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<ContribuicaoColaborador> ContribuicaoColaborador { get; set; }
        public virtual ICollection<ObjetivoColaborador> ObjetivoColaborador { get; set; }
        public virtual ICollection<PerformanceColaborador> PerformanceColaborador { get; set; }
        public virtual ICollection<RecomendacaoColaborador> RecomendacaoColaborador { get; set; }
    }
}
