//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloAvaliacao
    {
        public CicloAvaliacao()
        {
            this.AssociacaoCargoCompetencia = new HashSet<AssociacaoCargoCompetencia>();
            this.AvaliacaoColaborador = new HashSet<AvaliacaoColaborador>();
            this.AvaliacaoPDIColaborador = new HashSet<AvaliacaoPDIColaborador>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataInicioVigencia { get; set; }
        public System.DateTime DataFimVigencia { get; set; }
        public string URLCompetencia { get; set; }
        public string OrientacaoCompetencia { get; set; }
        public Nullable<System.DateTime> DataInicioObjetivosMetas { get; set; }
        public Nullable<System.DateTime> DataTerminoObjetivosMetas { get; set; }
        public string TituloOrientacaoObjetivosMetas { get; set; }
        public string TextoOrientacaoObjetivosMetas { get; set; }
        public Nullable<System.DateTime> DataInicioAutoAvaliacao { get; set; }
        public Nullable<System.DateTime> DataTerminoAutoAvaliacao { get; set; }
        public string TituloOrientacaoAutoAvaliacao { get; set; }
        public string TextoOrientacaoAutoAvaliacao { get; set; }
        public Nullable<System.DateTime> DataInicioAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DataTerminoAvaliacaoGestor { get; set; }
        public string TituloOrientacaoAvaliacaoGestor { get; set; }
        public string TextoOrientacaoAvaliacaoGestor { get; set; }
        public Nullable<System.DateTime> DataInicioGerenciamentoPDI { get; set; }
        public Nullable<System.DateTime> DataTerminoGerenciamentoPDI { get; set; }
        public Nullable<int> SituacaoCicloAvaliacao_ID { get; set; }
    
        public virtual ICollection<AssociacaoCargoCompetencia> AssociacaoCargoCompetencia { get; set; }
        public virtual ICollection<AvaliacaoColaborador> AvaliacaoColaborador { get; set; }
        public virtual ICollection<AvaliacaoPDIColaborador> AvaliacaoPDIColaborador { get; set; }
        public virtual SituacaoCicloAvaliacao SituacaoCicloAvaliacao { get; set; }
    }
}
