//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaColaborador
    {
        public MetaColaborador()
        {
            this.ObjetivoColaborador = new HashSet<ObjetivoColaborador>();
        }
    
        public int ID { get; set; }
        public string Meta { get; set; }
        public Nullable<int> ResultadoAtingidoColaborador_ID { get; set; }
    
        public virtual ResultadoAtingidoColaborador ResultadoAtingidoColaborador { get; set; }
        public virtual ICollection<ObjetivoColaborador> ObjetivoColaborador { get; set; }
    }
}
