//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvaliacaoDesempenhoContextEntities : DbContext
    {
        public AvaliacaoDesempenhoContextEntities()
            : base("name=AvaliacaoDesempenhoContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AssociacaoCargoCompetencia> AssociacaoCargoCompetencia { get; set; }
        public DbSet<AvaliacaoColaborador> AvaliacaoColaborador { get; set; }
        public DbSet<AvaliacaoGestor> AvaliacaoGestor { get; set; }
        public DbSet<AvaliacaoPDIColaborador> AvaliacaoPDIColaborador { get; set; }
        public DbSet<CicloAvaliacao> CicloAvaliacao { get; set; }
        public DbSet<CompetenciaColaborador> CompetenciaColaborador { get; set; }
        public DbSet<ContribuicaoColaborador> ContribuicaoColaborador { get; set; }
        public DbSet<DesenvolvimentoCompetencia> DesenvolvimentoCompetencia { get; set; }
        public DbSet<MetaColaborador> MetaColaborador { get; set; }
        public DbSet<ObjetivoColaborador> ObjetivoColaborador { get; set; }
        public DbSet<Papel> Papel { get; set; }
        public DbSet<ResultadoAtingidoColaborador> ResultadoAtingidoColaborador { get; set; }
        public DbSet<SituacaoCicloAvaliacao> SituacaoCicloAvaliacao { get; set; }
        public DbSet<StatusAvaliacaoColaborador> StatusAvaliacaoColaborador { get; set; }
        public DbSet<StatusPDI> StatusPDI { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
