//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecomendacaoColaborador
    {
        public int ID { get; set; }
        public int AvaliacaoColaborador_ID { get; set; }
        public int RecomendacaoDeRating { get; set; }
        public bool RecomendacaoDePromocao { get; set; }
        public string Justificativa { get; set; }
        public string JustificativaDaJustificativa { get; set; }
        public Nullable<int> RatingFinalPosCalibragem { get; set; }
        public string JustificativaRatingFinalPosCalibragem { get; set; }
        public Nullable<bool> IndicacaoPromocaoPosCalibragem { get; set; }
        public string JustificativaIndicacaoPromocaoPosCalibragem { get; set; }
    
        public virtual AvaliacaoColaborador AvaliacaoColaborador { get; set; }
    }
}
