//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaliacaoDesempenho.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.AvaliacaoColaborador = new HashSet<AvaliacaoColaborador>();
            this.AvaliacaoPDIColaborador = new HashSet<AvaliacaoPDIColaborador>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public int Papel_ID { get; set; }
        public Nullable<int> GestorRubiID { get; set; }
        public int UsuarioRubiID { get; set; }
        public int CodigoEmpresaRubiUD { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<AvaliacaoColaborador> AvaliacaoColaborador { get; set; }
        public virtual ICollection<AvaliacaoPDIColaborador> AvaliacaoPDIColaborador { get; set; }
        public virtual Papel Papel { get; set; }
    }
}
